run:
  concurrency: 4
  timeout: 3m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
output:
  formats:
    - format: colored-line-number
      path: stderr
  print-issued-lines: true
  print-linter-name: true
  sort-results: false
issues:
  uniq-by-line: true
linters:
  enable:
    - gosimple
    - staticcheck
    - unused
    - govet
    - unconvert
    - prealloc
    - nlreturn
    - goprintffuncname
    - revive
    - goimports
    - err113
    - godox
    - gocritic
    - goconst
    - gci
    - dupl
    - copyloopvar
    - govet
  disable-all: false
  presets:
    - bugs
    - unused
    - complexity
    - performance
  fast: false
