[Service]
URL = "http://localhost:30002"
Tags = ["internal", "secondary-node", "eu-west"]
    [ServiceMetaData]

# very verbose output, journal may rotate often
[Log]
DEBUG = true

[Prometheus]
Address = "localhost:9503" # turn off by set empty string

[MessageBroker]
URL = "nats://localhost:4222"
Username = "" # optional
Password = "" # optional

[PowerDNS]
URL = "http://localhost:18081"
APIToken = "0000"
ServerID = "localhost"
EventDelay = "0s"
APIWorker = 4

[AXFRPrimary]
Address = "127.0.0.1:20102"

[ZoneEventTopics]
Add = "zone.add"
Mod = "zone.modified"
Del = "zone.delete"

[ZoneDataTopics]
Prefix = "zonedata."

[ZoneStateTopics]
Prefix = "zonestate."

Secondaries = [
sec01.example.org,
sec02.example.org,
]
