[Service]
URL = "http://localhost:30000"
Cert = "/home/pdns-api-proxy/cert.pem"
Key = "/home/pdns-api-proxy/key.pem"
Tags = ["internal", "primary-node", "proxy"]
    [ServiceMetaData]

# very verbose output, journal may rotate often
[Log]
DEBUG = true

[Prometheus]
Address = "localhost:9502" # turn off by set empty string

[ServiceDiscovery]
URL = "http://localhost:8500"
HealthPingIntervall = "5s"
Username = "" # optional
Password = "" # optional

[MessageBroker]
URL = "nats://localhost:4222"
Username = "" # optional
Password = "" # optional

[PowerDNS]
URL = "http://localhost:8081"

[ZoneEventTopics]
Add = "zone.add"
Mod = "zone.modified"
Del = "zone.delete"