[Service]
URL = "http://localhost:30001"
Tags = ["external", "primary-node", "proxy"]
    [ServiceMetaData]

# very verbose output, journal may rotate often
[Log]
DEBUG = true

[Prometheus]
Address = "localhost:9500" # turn off by set empty string

[MessageBroker]
URL = "nats://localhost:4222"
Username = "" # optional
Password = "" # optional

[PowerDNS]
URL = "http://localhost:8081"
APIToken = "0000"
ServerID = "localhost"
AXFRTimeout = "2s"
AXFRAddress = "127.0.0.1:53"

[ZoneDataTopics]
Wildcard = "zonedata.>"