/*PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
//nolint:golint
package modelpowerdns

type Server struct {
	// Set to “Server”
	Type string `json:"type,omitempty"`
	// The id of the server, “localhost”
	ID string `json:"id,omitempty"`
	// “recursor” for the PowerDNS Recursor and “authoritative” for the Authoritative Server
	DaemonType string `json:"daemon_type,omitempty"`
	// The version of the server software
	Version string `json:"version,omitempty"`
	// The API endpoint for this server
	URL string `json:"url,omitempty"`
	// The API endpoint for this server’s configuration
	ConfigURL string `json:"config_url,omitempty"`
	// The API endpoint for this server’s zones
	ZonesURL string `json:"zones_url,omitempty"`
}
