/*PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package modelpowerdns

type SimpleStatisticItem struct {
	// Item name
	Name string `json:"name,omitempty"`
	// Item value
	Value string `json:"value,omitempty"`
}
