/*
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
//nolint:golint
package modelpowerdns

type RingStatisticItem struct {
	// Item name
	Name string `json:"name,omitempty"`
	// Set to \"RingStatisticItem\"
	Type_ string `json:"type,omitempty"`
	// Ring size
	Size int32 `json:"size,omitempty"`
	// Named values
	Value []SimpleStatisticItem `json:"value,omitempty"`
}
