/*PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
//nolint:lll,golint
package modelpowerdns

// A TSIG key that can be used to authenticate NOTIFYs and AXFRs.
type TsigKey struct {
	// The name of the key
	Name string `json:"name,omitempty"`
	// The ID for this key, used in the TSIGkey URL endpoint.
	ID string `json:"id,omitempty"`
	// The algorithm of the TSIG key
	Algorithm string `json:"algorithm,omitempty"`
	// The Base64 encoded secret key, empty when listing keys. MAY be empty when POSTing to have the server generate the key material
	Key string `json:"key,omitempty"`
	// Set to \"TSIGKey\"
	Type_ string `json:"type,omitempty"`
}
