sequenceDiagram
  participant a as [external-client]
  participant b as internal-proxy
  participant c as [PowerDNS API]
  participant e as external-proxy
  participant d as [Message Broker]
  participant f as secondary-syncer
  a->>+b: Zone-Add
  b-xd: {ZONE.ADD}
  d-xf: {ZONE.ADD}
  f->>+d: Get-Zone-Data
  d->>+e: Get-Zone-Data
  e->>+c: Get-Zone-Data
  c-->>-e: Zone-Data
  e-->>-d: Zone-Data
  d-->>-f: Zone-Data
  b->>+c: Zone-Add
  c-->>-b: Zone-Add-Successful
  b-->>-a: Zone-Add-Successful
  Note over b,c: pdns-primary
  Note over d,e: pdns-primary
  Note over f: pdns-secondary