sequenceDiagram
participant a as health-checker
participant b as [Primary PowerDNS API]
participant c as [Message Broker]
participant e as [Secondary PowerDNS]
loop Every Quarter of an hour
a->>+b: Get-Zones-Serial
b-->>-a: All-Zones-Serial
a->>+c: Get-Active-Secondaries
c-->>-a: Active-Secondaries
loop All Secondaries
loop All Zones
a->>+e: Get-Zone-Serial
e-->>-a: Zone-Serial
end
end
a-xc: {Zone.Change}
end
Note over a,c: pdns-primary
Note over e: pdns-secondary