[Service]
URL = "http://localhost:30001"
Tags = ["internal", "primary-node", "health", "check"]
    [ServiceMetaData]

# very verbose output, journal may rotate often
[Log]
DEBUG = true

[Prometheus]
Address = "localhost:9501" # turn off by set empty string

[MessageBroker]
URL = "nats://localhost:4222"
Username = "" # optional
Password = "" # optional

[PowerDNS]
URL = "http://localhost:8081"
APIToken = "0000"
ServerID = "localhost"

[ZoneEventTopics]
Add = "zone.add"
Mod = "zone.modified"
Del = "zone.delete"

[ZoneStateTopics]
Prefix = "zonestate."

[HealthChecks]
EventCheckWaitTime = "20s"
ActiveZoneSecondaryRefreshIntervall = "5m"
PeriodicalCheckIntervall = "15m"
NSEC3CheckIntervall = "15m"

Secondaries = [
sec01.example.org,
sec02.example.org,
]